mkdir -p log
mkdir -p snapshot
# driving scene
# python train_transfer_driving.py -u --batch-size 15 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt --VPN-weights ./pretrained/VPN_pretrain_RGB.pth.tar
# srun -p Segmentation --gres=gpu:1 -n1 --job-name=bw_vpn python -u train_transfer_driving.py --task-id 3-1 --iter-size-G 3 --iter-size-D 1 --snapshot-dir ./snapshot --batch-size 10 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt 2>&1 > log/vpn.log &
# srun -p Segmentation --gres=gpu:1 -n1 --job-name=2-1bw_vpn python -u train_transfer_driving.py --task-id 2-1 --iter-size-G 2 --iter-size-D 1 --snapshot-dir ./snapshot --batch-size 10 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt 2>&1 > log/vpn.log &
# srun -p Segmentation --gres=gpu:1 -n1 --job-name=1-1bw_vpn python -u train_transfer_driving.py --task-id 1-1 --iter-size-G 1 --iter-size-D 1 --snapshot-dir ./snapshot --batch-size 10 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt 2>&1 > log/vpn.log &
# srun -p Segmentation --gres=gpu:1 -n1 --job-name=pretra_bw_vpn python -u train_transfer_driving.py --task-id pretrained_1-1 --iter-size-G 1 --snapshot-dir ./snapshot --iter-size-D 1 --batch-size 10 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt --VPN-weights ./pretrained/VPN_pretrain_RGB.pth.tar 2>&1 > log/vpn.log &
# srun -p Segmentation --gres=gpu:1 -n1 --job-name=lr_bw_vpn python -u train_transfer_driving.py --task-id lr1e-5_1-1 --learning-rate-D 1e-5 --snapshot-dir ./snapshot --iter-size-G 1 --iter-size-D 1 --batch-size 10 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt --VPN-weights ./pretrained/VPN_pretrain_RGB.pth.tar 2>&1 > log/vpn.log &
# srun -p Segmentation --gres=gpu:1 -n1 --job-name=lr5e-6_bw_vpn python -u train_transfer_driving.py --task-id lr5e-6_1-1 --learning-rate-D 5e-6 --snapshot-dir ./snapshot --iter-size-G 1 --iter-size-D 1 --batch-size 10 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt --VPN-weights ./pretrained/VPN_pretrain_RGB.pth.tar 2>&1 > log/vpn.log &
# srun -p Segmentation --gres=gpu:4 -n1 --job-name=3-1-bw_vpn python -u train_transfer_driving.py --task-id carla_6 --num-class 94 --learning-rate-D 1e-5 --iter-size-G 3 --iter-size-D 1 --snapshot-dir ./snapshot --batch-size 20 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt --VPN-weights ./pretrained/VPN_pretrain_RGB.pth.tar 2>&1 > log/vpn.log &
# srun -p AD --gres=gpu:8 -n1 --job-name=carla_6 python -u train_carla.py --fc-dim 256 --use-depth false --use-mask false --num-class 13 --transform-type fc --input-resolution 400 --label-res 25 --store-name carla_6 --n-views 6 --batch-size 48 -j 10 --data_root ./data/Carla_Dataset_v1/ --train-list tools/train_source_list.txt --eval-list tools/val_source_list.txt 2>&1 > log/carla_6.log &
# srun -p AD --gres=gpu:4 -n1 --job-name=1-1-bw_vpn python -u train_transfer_driving.py --task-id carla2nuscene-rgb-lr＠3e-6-feat-level --num-class 94 --learning-rate-D 3e-6 --iter-size-G 1 --iter-size-D 1 --snapshot-dir ./snapshot --batch-size 20 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt --VPN-weights ./model_pretrained/carla_6_best.pth.tar
# srun -p AD --gres=gpu:4 -n1 --job-name=1-1-bw_vpn python -u train_transfer_driving.py --task-id carla2nuscene-rgb-lr＠1e-5-feat-level --num-class 94 --learning-rate-D 1e-5 --iter-size-G 1 --iter-size-D 1 --snapshot-dir ./snapshot --batch-size 20 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt --VPN-weights ./model_pretrained/carla_6_best.pth.tar
# srun -p AD --gres=gpu:4 -n1 --job-name=1-1-bw_vpn python -u train_transfer_driving.py --task-id carla2nuscene-rgb-lr＠1e-6-feat-level --num-class 94 --learning-rate-D 1e-6 --iter-size-G 1 --iter-size-D 1 --snapshot-dir ./snapshot --batch-size 20 --tensorboard true --n-views 6 --train_source_list tools/train_source_list.txt --train_target_list tools/train_target_list.txt --VPN-weights ./model_pretrained/carla_6_best.pth.tar
# 1e-5
# 1e-6
srun -p AD --gres=gpu:4 -n1 --job-name=test_bw_vpn python test_carla.py --fc-dim 256 --use-depth false --use-mask false --transform-type fc --input-resolution 400 --label-res 25 --store-name 6_view --n-views 6 --batch-size 4 --test-views 6 --data_root ./data/Carla_Dataset_v1/ --eval-list tools/val_source_list.txt --num-class 94 -j 10 --weights model/carla_6_best.pth.tar
